# Generated by Django 5.2.7 on 2025-10-28 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('distributor', models.CharField(blank=True, max_length=200)),
                ('producer', models.CharField(blank=True, max_length=200)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('kobis_id', models.CharField(blank=True, max_length=50)),
                ('kmdb_id', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BoxOfficeMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('rank', models.PositiveIntegerField()),
                ('sales', models.BigIntegerField()),
                ('audience', models.BigIntegerField()),
                ('screens', models.IntegerField(blank=True, null=True)),
                ('show_count', models.IntegerField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to='main.movie')),
            ],
            options={
                'indexes': [models.Index(fields=['year', 'month', 'rank'], name='main_boxoff_year_3aa67a_idx')],
                'unique_together': {('movie', 'year', 'month', 'rank')},
            },
        ),
    ]
